[package]
name = "sfio-rustls-util"
version = "0.1.0"
edition = "2021"

[dependencies]
rx509 = "^0.2"
rustls = { version = "^0.21", features = ["dangerous_configuration"] }
rustls-webpki = { version = "^0.100.1" }
sfio-pem-util = { git = "https://github.com/stepfunc/pem-util.git" }

